us20a // items sort only
matschi3/capstone pull request #46
Opened 2023-07-17 14:39 UTC by matschi3

Sort `items` for its date `assembled` or `sold`.
`dateAssembled` is the date displayed on top of each `itemCard`.
`dateSold` is not displayed so you gotta believe, but its working as like the `dateAssembled`  ;)

[US20a](https://github.com/matschi3/capstone/issues/42)

2023-07-17 16:34 UTC, JonasDaJones commented
lgtm

2023-07-18 09:13 UTC, matschi3 commented
// edit
now it is totally working

2023-07-18 10:16 UTC, djfarly requested changes
Hej Nils!

Sorting things can be quite challenging but you did great.
My suggestions mostly are about the actual state values you use and the filter input you build. :)

Keep going! 🎉

2023-07-18 10:16 UTC, djfarly commented on pages/items.js
> +    if (sorting === "verbaut(neueste)") {
```suggestion
    if (sorting === "dateAssembled(DESC)") {
```

2023-07-18 10:16 UTC, djfarly commented on pages/items.js
> +    } else if (sorting === "verbaut(älteste)") {
```suggestion
    } else if (sorting === "dateAssembled(ASC)") {
```

2023-07-18 12:36 UTC, matschi3 commented on pages/items.js
> +  const sortedItems = items.sort((a, b) => {
oh yes sure i will. Better to do so :)

2023-07-18 13:07 UTC, matschi3 commented on pages/items.js
> +              valueToSet: "verbaut(neueste)",
oh yes i need to keep the german out of the code (except for labels and stuff)
descending/ascending is a great suggestion i will go with :)
Thanks

2023-07-18 13:15 UTC, matschi3 commented on pages/items.js
> +          filters={[
Great suggestion! Thanks a lot @djfarly . Sth like this i was trying to build, when i coded the StyledFilter component for filtering the PartCards. But due to i wanted to keep it reusable for now, i kinda let it grow a little big and messy. 
My previous filters Object ( now 'options' ) was a needle in my eye when i build. Luckily its gone now and filters are working fine! 🎉

2023-07-18 13:22 UTC, matschi3 commented
// edited
less code, still working fine

2023-07-18 14:01 UTC, djfarly approved these changes
looking good 👍

2023-07-18 14:44 UTC, merged